### ISSUE TITLE
client crash 1.20.1/3.1.0 Beta

### ISSUE THREAD

**Issue by Koopaxd** [JunePrimavera/Minecraft-Vanilla-Notebook#84] opened 2024-07-31 14:33 UTC
when renaming the book you cant enter spaces, it instantly crashes the game if you do

The logs that show at the point of crashing:

[16:27:50] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:954) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: Notebook\my \1.notebookpage (The system cant find the path)
	at com.june.notebook.NotebookScreen.readPage(NotebookScreen.java:103) ~[Notebook-3.1.0+1.20.1.jar:?]
	at com.june.notebook.NotebookScreen.method_25394(NotebookScreen.java:299) ~[Notebook-3.1.0+1.20.1.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	... 6 more
Caused by: java.io.FileNotFoundException: Notebook\my \1.notebookpage (Das System kann den angegebenen Pfad nicht finden)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(Unknown Source) ~[?:?]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:?]
	at java.util.Scanner.<init>(Unknown Source) ~[?:?]
	at com.june.notebook.NotebookScreen.readPage(NotebookScreen.java:96) ~[Notebook-3.1.0+1.20.1.jar:?]
	at com.june.notebook.NotebookScreen.method_25394(NotebookScreen.java:299) ~[Notebook-3.1.0+1.20.1.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	... 6 more

**Comment by JunePrimavera** [comment] 2024-07-31 14:42
I can't reproduce this on the latest version of the mod, but it did have issues with spaces not registering correctly so this is now fixed as of a01ed15

**Closed** 2024-08-01 09:00 UTC
Labels: Bug
